spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/messenger
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.websocket.server.undertow.supports-close=true
spring.main.web-application-type=servlet
#SSL ???? ???????? ??? ?????
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=${P12_PASSWORD}
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=tomcat
#server.servlet.session.cookie.secure=true
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#ENV CONF
spring.config.import=optional:file:.env[.properties]
# Server
server.port=25565